services:
  movera:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MOVERA_CONFIG=/config/movera.yaml
    volumes:
      - ./config:/config
      - ./downloads:/watch/downloads
      - ./tests:/tests